load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "CommonTestingMavenTest",
    srcs = ["CommonTestingMavenTest.kt"],
    test_class = "org.wfanet.measurement.edpcomponents.meta.CommonTestingMavenTest",
    deps = [
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_wfanet_measurement_common_testing",
    ],
)

kt_jvm_test(
    name = "MetaImpressionQueryFunctionTest",
    srcs = ["MetaImpressionQueryFunctionTest.kt"],
    test_class = "org.wfanet.measurement.edpcomponents.meta.MetaImpressionQueryFunctionTest",
    deps = [
        "//src/main/kotlin/org/wfanet/measurement/edpcomponents/meta:data_provider_impression_query_kt_jvm_proto",
        "//src/main/kotlin/org/wfanet/measurement/edpcomponents/meta:meta_impression_query",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
    ],
)

# Manual: hits a deployed Cloud Function. See README.md.
kt_jvm_test(
    name = "DeployedFunctionTest",
    srcs = ["DeployedFunctionTest.kt"],
    tags = [
        "external",
        "manual",
    ],
    test_class = "org.wfanet.measurement.edpcomponents.meta.DeployedFunctionTest",
    deps = [
        "//src/main/kotlin/org/wfanet/measurement/edpcomponents/meta:data_provider_impression_query_kt_jvm_proto",
        "//src/main/kotlin/org/wfanet/measurement/edpcomponents/meta:meta_impression_query",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

kt_jvm_test(
    name = "MetaMarketingApiInsightsClientTest",
    srcs = ["MetaMarketingApiInsightsClientTest.kt"],
    test_class = "org.wfanet.measurement.edpcomponents.meta.MetaMarketingApiInsightsClientTest",
    deps = [
        "//src/main/kotlin/org/wfanet/measurement/edpcomponents/meta:data_provider_impression_query_kt_jvm_proto",
        "//src/main/kotlin/org/wfanet/measurement/edpcomponents/meta:meta_impression_query",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_jetbrains_kotlin_kotlin_test",
    ],
)
